module.exports = [
  {
    name: 'nbsp',
    number: 160,
    description: 'no-break space = non-breaking space, U+00A0 ISOnum',
    tags: [' ', 'space'],
***REMOVED***,
  {
    name: 'iexcl',
    number: 161,
    description: 'inverted exclamation mark, U+00A1 ISOnum',
    tags: ['¡', 'exclamation', 'mark', '!'],
***REMOVED***,
  {
    name: 'cent',
    number: 162,
    description: 'cent sign, U+00A2 ISOnum',
    tags: ['¢', 'cent', 'c'],
***REMOVED***,
  {
    name: 'pound',
    number: 163,
    description: 'pound sign, U+00A3 ISOnum',
    tags: ['£', '#', 'pound'],
***REMOVED***,
  {
    name: 'curren',
    number: 164,
    description: 'currency sign, U+00A4 ISOnum',
    tags: ['¤', 'currency'],
***REMOVED***,
  {
    name: 'yen',
    number: 165,
    description: 'yen sign = yuan sign, U+00A5 ISOnum',
    tags: ['¥', 'yen', 'y'],
***REMOVED***,
  {
    name: 'brvbar',
    number: 166,
    description: 'broken bar = broken vertical bar, U+00A6 ISOnum',
    tags: ['¦', 'bar', 'vertical', '|'],
***REMOVED***,
  {
    name: 'sect',
    number: 167,
    description: 'section sign, U+00A7 ISOnum',
    tags: ['§', 'section', 's'],
***REMOVED***,
  {
    name: 'uml',
    number: 168,
    description: 'diaeresis = spacing diaeresis, U+00A8 ISOdia',
    tags: ['¨', '"'],
***REMOVED***,
  {
    name: 'copy',
    number: 169,
    description: 'copyright sign, U+00A9 ISOnum',
    tags: ['©', '(c)', 'c', 'copyright'],
***REMOVED***,
  {
    name: 'ordf',
    number: 170,
    description: 'feminine ordinal indicator, U+00AA ISOnum',
    tags: ['ª', 'a'],
***REMOVED***,
  {
    name: 'laquo',
    number: 171,
    description:
      'left-pointing double angle quotation mark = left pointing guillemet, U+00AB ISOnum',
    tags: ['«', '<', '<<', 'double'],
***REMOVED***,
  {
    name: 'not',
    number: 172,
    description: 'not sign, U+00AC ISOnum',
    tags: ['¬', 'not', '-'],
***REMOVED***,
  {
    name: 'shy',
    number: 173,
    description: 'soft hyphen = discretionary hyphen, U+00AD ISOnum',
    tags: ['­'],
***REMOVED***,
  {
    name: 'reg',
    number: 174,
    description: 'registered sign = registered trade mark sign, U+00AE ISOnum',
    tags: ['®', '(r)', 'r', 'registered'],
***REMOVED***,
  {
    name: 'macr',
    number: 175,
    description:
      'macron = spacing macron = overline = APL overbar, U+00AF ISOdia',
    tags: ['¯', '-', 'overline'],
***REMOVED***,
  {
    name: 'deg',
    number: 176,
    description: 'degree sign, U+00B0 ISOnum',
    tags: ['°', 'degree', 'o'],
***REMOVED***,
  {
    name: 'plusmn',
    number: 177,
    description: 'plus-minus sign = plus-or-minus sign, U+00B1 ISOnum',
    tags: ['±', 'plus-minus', '+', '-', '+-'],
***REMOVED***,
  {
    name: 'sup2',
    number: 178,
    description:
      'superscript two = superscript digit two = squared, U+00B2 ISOnum',
    tags: ['²', 'superscript', 'two', '2'],
***REMOVED***,
  {
    name: 'sup3',
    number: 179,
    description:
      'superscript three = superscript digit three = cubed, U+00B3 ISOnum',
    tags: ['³', 'superscript', 'three', '3'],
***REMOVED***,
  {
    name: 'acute',
    number: 180,
    description: 'acute accent = spacing acute, U+00B4 ISOdia',
    tags: ['´', 'acute', "'", '`'],
***REMOVED***,
  {
    name: 'micro',
    number: 181,
    description: 'micro sign, U+00B5 ISOnum',
    tags: ['µ', 'micro', 'u'],
***REMOVED***,
  {
    name: 'para',
    number: 182,
    description: 'pilcrow sign = paragraph sign, U+00B6 ISOnum',
    tags: ['¶', 'pilcrow', 'enter', 'return', 'n'],
***REMOVED***,
  {
    name: 'middot',
    number: 183,
    description:
      'middle dot = Georgian comma = Greek middle dot, U+00B7 ISOnum',
    tags: ['·', '.', 'middle', 'dot'],
***REMOVED***,
  {
    name: 'cedil',
    number: 184,
    description: 'cedilla = spacing cedilla, U+00B8 ISOdia',
    tags: ['¸', ','],
***REMOVED***,
  {
    name: 'sup1',
    number: 185,
    description: 'superscript one = superscript digit one, U+00B9 ISOnum',
    tags: ['¹', '1', 'superscript', 'one'],
***REMOVED***,
  {
    name: 'ordm',
    number: 186,
    description: 'masculine ordinal indicator, U+00BA ISOnum',
    tags: ['º', 'o', 'ordinal'],
***REMOVED***,
  {
    name: 'raquo',
    number: 187,
    description:
      'right-pointing double angle quotation mark = right pointing guillemet, U+00BB ISOnum',
    tags: ['»', 'right-pointing', 'double', '>', '>>'],
***REMOVED***,
  {
    name: 'frac14',
    number: 188,
    description:
      'vulgar fraction one quarter = fraction one quarter, U+00BC ISOnum',
    tags: ['¼', 'fraction', '1/4', 'quarter'],
***REMOVED***,
  {
    name: 'frac12',
    number: 189,
    description: 'vulgar fraction one half = fraction one half, U+00BD ISOnum',
    tags: ['½', 'fraction', 'half', '1/2'],
***REMOVED***,
  {
    name: 'frac34',
    number: 190,
    description:
      'vulgar fraction three quarters = fraction three quarters, U+00BE ISOnum',
    tags: ['¾', 'fraction', 'quarters', '3/4'],
***REMOVED***,
  {
    name: 'iquest',
    number: 191,
    description: 'inverted question mark = turned question mark, U+00BF ISOnum',
    tags: ['¿', '?', 'question', 'inverted'],
***REMOVED***,
  {
    name: 'Agrave',
    number: 192,
    description:
      'latin capital letter A with grave = latin capital letter A grave, U+00C0 ISOlat1',
    tags: ['À', 'A', 'grave'],
***REMOVED***,
  {
    name: 'Aacute',
    number: 193,
    description: 'latin capital letter A with acute, U+00C1 ISOlat1',
    tags: ['Á', 'A', 'acute'],
***REMOVED***,
  {
    name: 'Acirc',
    number: 194,
    description: 'latin capital letter A with circumflex, U+00C2 ISOlat1',
    tags: ['Â', 'A', 'circumflex'],
***REMOVED***,
  {
    name: 'Atilde',
    number: 195,
    description: 'latin capital letter A with tilde, U+00C3 ISOlat1',
    tags: ['Ã', 'A', 'tilde'],
***REMOVED***,
  {
    name: 'Auml',
    number: 196,
    description: 'latin capital letter A with diaeresis, U+00C4 ISOlat1',
    tags: ['Ä', 'A', 'diaeresis'],
***REMOVED***,
  {
    name: 'Aring',
    number: 197,
    description:
      'latin capital letter A with ring above = latin capital letter A ring, U+00C5 ISOlat1',
    tags: ['Å', 'A', 'ring'],
***REMOVED***,
  {
    name: 'AElig',
    number: 198,
    description:
      'latin capital letter AE = latin capital ligature AE, U+00C6 ISOlat1',
    tags: ['Æ', 'AE'],
***REMOVED***,
  {
    name: 'Ccedil',
    number: 199,
    description: 'latin capital letter C with cedilla, U+00C7 ISOlat1',
    tags: ['Ç', 'C', 'cedilla'],
***REMOVED***,
  {
    name: 'Egrave',
    number: 200,
    description: 'latin capital letter E with grave, U+00C8 ISOlat1',
    tags: ['È', 'E', 'grave'],
***REMOVED***,
  {
    name: 'Eacute',
    number: 201,
    description: 'latin capital letter E with acute, U+00C9 ISOlat1',
    tags: ['É', 'E', 'acute'],
***REMOVED***,
  {
    name: 'Ecirc',
    number: 202,
    description: 'latin capital letter E with circumflex, U+00CA ISOlat1',
    tags: ['Ê', 'E', 'circumflex'],
***REMOVED***,
  {
    name: 'Euml',
    number: 203,
    description: 'latin capital letter E with diaeresis, U+00CB ISOlat1',
    tags: ['Ë', 'E', 'diaeresis'],
***REMOVED***,
  {
    name: 'Igrave',
    number: 204,
    description: 'latin capital letter I with grave, U+00CC ISOlat1',
    tags: ['Ì', 'I', 'grave', 'L'],
***REMOVED***,
  {
    name: 'Iacute',
    number: 205,
    description: 'latin capital letter I with acute, U+00CD ISOlat1',
    tags: ['Í', 'I', 'acute', 'L'],
***REMOVED***,
  {
    name: 'Icirc',
    number: 206,
    description: 'latin capital letter I with circumflex, U+00CE ISOlat1',
    tags: ['Î', 'I', 'circumflex', 'L'],
***REMOVED***,
  {
    name: 'Iuml',
    number: 207,
    description: 'latin capital letter I with diaeresis, U+00CF ISOlat1',
    tags: ['Ï', 'I', 'diaeresis', 'L'],
***REMOVED***,
  {
    name: 'ETH',
    number: 208,
    description: 'latin capital letter ETH, U+00D0 ISOlat1',
    tags: ['Ð', 'ETH', 'D'],
***REMOVED***,
  {
    name: 'Ntilde',
    number: 209,
    description: 'latin capital letter N with tilde, U+00D1 ISOlat1',
    tags: ['Ñ', 'N', 'tilde'],
***REMOVED***,
  {
    name: 'Ograve',
    number: 210,
    description: 'latin capital letter O with grave, U+00D2 ISOlat1',
    tags: ['Ò', 'O', 'grave'],
***REMOVED***,
  {
    name: 'Oacute',
    number: 211,
    description: 'latin capital letter O with acute, U+00D3 ISOlat1',
    tags: ['Ó', 'O', 'acute'],
***REMOVED***,
  {
    name: 'Ocirc',
    number: 212,
    description: 'latin capital letter O with circumflex, U+00D4 ISOlat1',
    tags: ['Ô', 'O', 'circumflex'],
***REMOVED***,
  {
    name: 'Otilde',
    number: 213,
    description: 'latin capital letter O with tilde, U+00D5 ISOlat1',
    tags: ['Õ', 'O', 'tilde'],
***REMOVED***,
  {
    name: 'Ouml',
    number: 214,
    description: 'latin capital letter O with diaeresis, U+00D6 ISOlat1',
    tags: ['Ö', 'O', 'diaeresis'],
***REMOVED***,
  {
    name: 'times',
    number: 215,
    description: 'multiplication sign, U+00D7 ISOnum',
    tags: ['×', 'multiplication', 'x', 'times'],
***REMOVED***,
  {
    name: 'Oslash',
    number: 216,
    description:
      'latin capital letter O with stroke = latin capital letter O slash, U+00D8 ISOlat1',
    tags: ['Ø', 'O', 'stroke', 'slash'],
***REMOVED***,
  {
    name: 'Ugrave',
    number: 217,
    description: 'latin capital letter U with grave, U+00D9 ISOlat1',
    tags: ['Ù', 'U', 'grave'],
***REMOVED***,
  {
    name: 'Uacute',
    number: 218,
    description: 'latin capital letter U with acute, U+00DA ISOlat1',
    tags: ['Ú', 'U', 'acute'],
***REMOVED***,
  {
    name: 'Ucirc',
    number: 219,
    description: 'latin capital letter U with circumflex, U+00DB ISOlat1',
    tags: ['Û', 'U', 'circumflex'],
***REMOVED***,
  {
    name: 'Uuml',
    number: 220,
    description: 'latin capital letter U with diaeresis, U+00DC ISOlat1',
    tags: ['Ü', 'U', 'diaeresis'],
***REMOVED***,
  {
    name: 'Yacute',
    number: 221,
    description: 'latin capital letter Y with acute, U+00DD ISOlat1',
    tags: ['Ý', 'Y', 'acute'],
***REMOVED***,
  {
    name: 'THORN',
    number: 222,
    description: 'latin capital letter THORN, U+00DE ISOlat1',
    tags: ['Þ', 'THORN', 'P'],
***REMOVED***,
  {
    name: 'szlig',
    number: 223,
    description: 'latin small letter sharp s = ess-zed, U+00DF ISOlat1',
    tags: ['ß', 'b', 'beta', 'ess-zed', 's'],
***REMOVED***,
  {
    name: 'agrave',
    number: 224,
    description:
      'latin small letter a with grave = latin small letter a grave, U+00E0 ISOlat1',
    tags: ['à', 'a', 'grave'],
***REMOVED***,
  {
    name: 'aacute',
    number: 225,
    description: 'latin small letter a with acute, U+00E1 ISOlat1',
    tags: ['á', 'a', 'acute'],
***REMOVED***,
  {
    name: 'acirc',
    number: 226,
    description: 'latin small letter a with circumflex, U+00E2 ISOlat1',
    tags: ['â', 'a', 'circumflex'],
***REMOVED***,
  {
    name: 'atilde',
    number: 227,
    description: 'latin small letter a with tilde, U+00E3 ISOlat1',
    tags: ['ã', 'a', 'tilde'],
***REMOVED***,
  {
    name: 'auml',
    number: 228,
    description: 'latin small letter a with diaeresis, U+00E4 ISOlat1',
    tags: ['ä', 'a', 'diaeresis'],
***REMOVED***,
  {
    name: 'aring',
    number: 229,
    description:
      'latin small letter a with ring above = latin small letter a ring, U+00E5 ISOlat1',
    tags: ['å', 'a', 'ring'],
***REMOVED***,
  {
    name: 'aelig',
    number: 230,
    description:
      'latin small letter ae = latin small ligature ae, U+00E6 ISOlat1',
    tags: ['æ', 'ae'],
***REMOVED***,
  {
    name: 'ccedil',
    number: 231,
    description: 'latin small letter c with cedilla, U+00E7 ISOlat1',
    tags: ['ç', 'c', 'cedilla'],
***REMOVED***,
  {
    name: 'egrave',
    number: 232,
    description: 'latin small letter e with grave, U+00E8 ISOlat1',
    tags: ['è', 'e', 'grave'],
***REMOVED***,
  {
    name: 'eacute',
    number: 233,
    description: 'latin small letter e with acute, U+00E9 ISOlat1',
    tags: ['é', 'e', 'acute'],
***REMOVED***,
  {
    name: 'ecirc',
    number: 234,
    description: 'latin small letter e with circumflex, U+00EA ISOlat1',
    tags: ['ê', 'e', 'circumflex'],
***REMOVED***,
  {
    name: 'euml',
    number: 235,
    description: 'latin small letter e with diaeresis, U+00EB ISOlat1',
    tags: ['ë', 'e', 'diaeresis'],
***REMOVED***,
  {
    name: 'igrave',
    number: 236,
    description: 'latin small letter i with grave, U+00EC ISOlat1',
    tags: ['ì', 'i', 'grave', 'L'],
***REMOVED***,
  {
    name: 'iacute',
    number: 237,
    description: 'latin small letter i with acute, U+00ED ISOlat1',
    tags: ['í', 'i', 'acute', 'L'],
***REMOVED***,
  {
    name: 'icirc',
    number: 238,
    description: 'latin small letter i with circumflex, U+00EE ISOlat1',
    tags: ['î', 'i', 'circumflex', 'L'],
***REMOVED***,
  {
    name: 'iuml',
    number: 239,
    description: 'latin small letter i with diaeresis, U+00EF ISOlat1',
    tags: ['ï', 'i', 'diaeresis', 'L'],
***REMOVED***,
  {
    name: 'eth',
    number: 240,
    description: 'latin small letter eth, U+00F0 ISOlat1',
    tags: ['ð', 'eth', 'o'],
***REMOVED***,
  {
    name: 'ntilde',
    number: 241,
    description: 'latin small letter n with tilde, U+00F1 ISOlat1',
    tags: ['ñ', 'n', 'tilde'],
***REMOVED***,
  {
    name: 'ograve',
    number: 242,
    description: 'latin small letter o with grave, U+00F2 ISOlat1',
    tags: ['ò', 'o', 'grave'],
***REMOVED***,
  {
    name: 'oacute',
    number: 243,
    description: 'latin small letter o with acute, U+00F3 ISOlat1',
    tags: ['ó', 'o', 'acute'],
***REMOVED***,
  {
    name: 'ocirc',
    number: 244,
    description: 'latin small letter o with circumflex, U+00F4 ISOlat1',
    tags: ['ô', 'o', 'circumflex'],
***REMOVED***,
  {
    name: 'otilde',
    number: 245,
    description: 'latin small letter o with tilde, U+00F5 ISOlat1',
    tags: ['õ', 'o', 'tilde'],
***REMOVED***,
  {
    name: 'ouml',
    number: 246,
    description: 'latin small letter o with diaeresis, U+00F6 ISOlat1',
    tags: ['ö', 'o', 'diaeresis'],
***REMOVED***,
  {
    name: 'divide',
    number: 247,
    description: 'division sign, U+00F7 ISOnum',
    tags: ['÷', 'division', '/', 'div'],
***REMOVED***,
  {
    name: 'oslash',
    number: 248,
    description:
      'latin small letter o with stroke, = latin small letter o slash, U+00F8 ISOlat1',
    tags: ['ø', 'o', 'stroke', 'slash'],
***REMOVED***,
  {
    name: 'ugrave',
    number: 249,
    description: 'latin small letter u with grave, U+00F9 ISOlat1',
    tags: ['ù', 'u', 'grave'],
***REMOVED***,
  {
    name: 'uacute',
    number: 250,
    description: 'latin small letter u with acute, U+00FA ISOlat1',
    tags: ['ú', 'u', 'acute'],
***REMOVED***,
  {
    name: 'ucirc',
    number: 251,
    description: 'latin small letter u with circumflex, U+00FB ISOlat1',
    tags: ['û', 'u', 'circumflex'],
***REMOVED***,
  {
    name: 'uuml',
    number: 252,
    description: 'latin small letter u with diaeresis, U+00FC ISOlat1',
    tags: ['ü', 'u', 'diaeresis'],
***REMOVED***,
  {
    name: 'yacute',
    number: 253,
    description: 'latin small letter y with acute, U+00FD ISOlat1',
    tags: ['ý', 'y', 'acute'],
***REMOVED***,
  {
    name: 'thorn',
    number: 254,
    description: 'latin small letter thorn, U+00FE ISOlat1',
    tags: ['þ', 'p', 'thorn'],
***REMOVED***,
  {
    name: 'yuml',
    number: 255,
    description: 'latin small letter y with diaeresis, U+00FF ISOlat1',
    tags: ['ÿ', 'y', 'diaeresis'],
***REMOVED***,
  {
    name: 'fnof',
    number: 402,
    description: 'latin small f with hook = function = florin, U+0192 ISOtech',
    tags: ['ƒ', 'f', 'hook', 'function', 'florin'],
***REMOVED***,
  {
    name: 'Alpha',
    number: 913,
    description: 'greek capital letter alpha, U+0391',
    tags: ['?', 'a', 'alpha'],
***REMOVED***,
  {
    name: 'Beta',
    number: 914,
    description: 'greek capital letter beta, U+0392',
    tags: ['?', 'B', 'beta'],
***REMOVED***,
  {
    name: 'Gamma',
    number: 915,
    description: 'greek capital letter gamma, U+0393 ISOgrk3',
    tags: ['G', 'gamma', 'L'],
***REMOVED***,
  {
    name: 'Delta',
    number: 916,
    description: 'greek capital letter delta, U+0394 ISOgrk3',
    tags: ['?', 'delta', 'triangle'],
***REMOVED***,
  {
    name: 'Epsilon',
    number: 917,
    description: 'greek capital letter epsilon, U+0395',
    tags: ['?', 'e', 'epsilon'],
***REMOVED***,
  {
    name: 'Zeta',
    number: 918,
    description: 'greek capital letter zeta, U+0396',
    tags: ['?', 'z', 'zeta'],
***REMOVED***,
  {
    name: 'Eta',
    number: 919,
    description: 'greek capital letter eta, U+0397',
    tags: ['?', 'h', 'eta'],
***REMOVED***,
  {
    name: 'Theta',
    number: 920,
    description: 'greek capital letter theta, U+0398 ISOgrk3',
    tags: ['T', 'theta', 'o'],
***REMOVED***,
  {
    name: 'Iota',
    number: 921,
    description: 'greek capital letter iota, U+0399',
    tags: ['?', 'i', 'iota'],
***REMOVED***,
  {
    name: 'Kappa',
    number: 922,
    description: 'greek capital letter kappa, U+039A',
    tags: ['?', 'k', 'kappa'],
***REMOVED***,
  {
    name: 'Lambda',
    number: 923,
    description: 'greek capital letter lambda, U+039B ISOgrk3',
    tags: ['?', 'lambda', 'triangle'],
***REMOVED***,
  {
    name: 'Mu',
    number: 924,
    description: 'greek capital letter mu, U+039C',
    tags: ['?', 'm', 'mu'],
***REMOVED***,
  {
    name: 'Nu',
    number: 925,
    description: 'greek capital letter nu, U+039D',
    tags: ['?', 'n', 'nu'],
***REMOVED***,
  {
    name: 'Xi',
    number: 926,
    description: 'greek capital letter xi, U+039E ISOgrk3',
    tags: ['?', 'xi', 'e'],
***REMOVED***,
  {
    name: 'Omicron',
    number: 927,
    description: 'greek capital letter omicron, U+039F',
    tags: ['?', 'o', 'omicron'],
***REMOVED***,
  {
    name: 'Pi',
    number: 928,
    description: 'greek capital letter pi, U+03A0 ISOgrk3',
    tags: ['?', 'pi'],
***REMOVED***,
  {
    name: 'Rho',
    number: 929,
    description: 'greek capital letter rho, U+03A1',
    tags: ['?', 'p', 'rho'],
***REMOVED***,
  {
    name: 'Sigma',
    number: 931,
    description: 'greek capital letter sigma, U+03A3 ISOgrk3',
    tags: ['S', 'sigma', 'e'],
***REMOVED***,
  {
    name: 'Tau',
    number: 932,
    description: 'greek capital letter tau, U+03A4',
    tags: ['?', 't', 'tau'],
***REMOVED***,
  {
    name: 'Upsilon',
    number: 933,
    description: 'greek capital letter upsilon, U+03A5 ISOgrk3',
    tags: ['?', 'upsilon', 'y'],
***REMOVED***,
  {
    name: 'Phi',
    number: 934,
    description: 'greek capital letter phi, U+03A6 ISOgrk3',
    tags: ['F', 'o', 'phi'],
***REMOVED***,
  {
    name: 'Chi',
    number: 935,
    description: 'greek capital letter chi, U+03A7',
    tags: ['?', 'x', 'chi'],
***REMOVED***,
  {
    name: 'Psi',
    number: 936,
    description: 'greek capital letter psi, U+03A8 ISOgrk3',
    tags: ['?', 'y', 'psi'],
***REMOVED***,
  {
    name: 'Omega',
    number: 937,
    description: 'greek capital letter omega, U+03A9 ISOgrk3',
    tags: ['O', 'omega', 'o'],
***REMOVED***,
  {
    name: 'alpha',
    number: 945,
    description: 'greek small letter alpha, U+03B1 ISOgrk3',
    tags: ['a', 'alpha', 'a'],
***REMOVED***,
  {
    name: 'beta',
    number: 946,
    description: 'greek small letter beta, U+03B2 ISOgrk3',
    tags: ['ß', 'b', 'beta'],
***REMOVED***,
  {
    name: 'gamma',
    number: 947,
    description: 'greek small letter gamma, U+03B3 ISOgrk3',
    tags: ['?', 'y', 'gamma'],
***REMOVED***,
  {
    name: 'delta',
    number: 948,
    description: 'greek small letter delta, U+03B4 ISOgrk3',
    tags: ['d', 'd', 'delta', 'o'],
***REMOVED***,
  {
    name: 'epsilon',
    number: 949,
    description: 'greek small letter epsilon, U+03B5 ISOgrk3',
    tags: ['e', 'e', 'epsilon'],
***REMOVED***,
  {
    name: 'zeta',
    number: 950,
    description: 'greek small letter zeta, U+03B6 ISOgrk3',
    tags: ['?', 'z', 'zeta'],
***REMOVED***,
  {
    name: 'eta',
    number: 951,
    description: 'greek small letter eta, U+03B7 ISOgrk3',
    tags: ['?', 'n', 'eta'],
***REMOVED***,
  {
    name: 'theta',
    number: 952,
    description: 'greek small letter theta, U+03B8 ISOgrk3',
    tags: ['?', 'o', 'theta'],
***REMOVED***,
  {
    name: 'iota',
    number: 953,
    description: 'greek small letter iota, U+03B9 ISOgrk3',
    tags: ['?', 'i', 'l', 'iota'],
***REMOVED***,
  {
    name: 'kappa',
    number: 954,
    description: 'greek small letter kappa, U+03BA ISOgrk3',
    tags: ['?', 'k', 'kappa'],
***REMOVED***,
  {
    name: 'lambda',
    number: 955,
    description: 'greek small letter lambda, U+03BB ISOgrk3',
    tags: ['?', 'n', 'lambda', 'y'],
***REMOVED***,
  {
    name: 'mu',
    number: 956,
    description: 'greek small letter mu, U+03BC ISOgrk3',
    tags: ['µ', 'u', 'mu'],
***REMOVED***,
  {
    name: 'nu',
    number: 957,
    description: 'greek small letter nu, U+03BD ISOgrk3',
    tags: ['?', 'nu', 'v'],
***REMOVED***,
  {
    name: 'xi',
    number: 958,
    description: 'greek small letter xi, U+03BE ISOgrk3',
    tags: ['?', 'e', 'xi'],
***REMOVED***,
  {
    name: 'omicron',
    number: 959,
    description: 'greek small letter omicron, U+03BF NEW',
    tags: ['?', 'o', 'omicron'],
***REMOVED***,
  {
    name: 'pi',
    number: 960,
    description: 'greek small letter pi, U+03C0 ISOgrk3',
    tags: ['p', 'pi'],
***REMOVED***,
  {
    name: 'rho',
    number: 961,
    description: 'greek small letter rho, U+03C1 ISOgrk3',
    tags: ['?', 'p', 'o', 'rho'],
***REMOVED***,
  {
    name: 'sigmaf',
    number: 962,
    description: 'greek small letter final sigma, U+03C2 ISOgrk3',
    tags: ['?', 'c', 'sigma', 'final'],
***REMOVED***,
  {
    name: 'sigma',
    number: 963,
    description: 'greek small letter sigma, U+03C3 ISOgrk3',
    tags: ['s', 'o', 'sigma'],
***REMOVED***,
  {
    name: 'tau',
    number: 964,
    description: 'greek small letter tau, U+03C4 ISOgrk3',
    tags: ['t', 't', 'tau'],
***REMOVED***,
  {
    name: 'upsilon',
    number: 965,
    description: 'greek small letter upsilon, U+03C5 ISOgrk3',
    tags: ['?', 'u', 'upsilon'],
***REMOVED***,
  {
    name: 'phi',
    number: 966,
    description: 'greek small letter phi, U+03C6 ISOgrk3',
    tags: ['f', 'y', 'phi'],
***REMOVED***,
  {
    name: 'chi',
    number: 967,
    description: 'greek small letter chi, U+03C7 ISOgrk3',
    tags: ['?', 'x', 'chi'],
***REMOVED***,
  {
    name: 'psi',
    number: 968,
    description: 'greek small letter psi, U+03C8 ISOgrk3',
    tags: ['?', 'y', 'psi'],
***REMOVED***,
  {
    name: 'omega',
    number: 969,
    description: 'greek small letter omega, U+03C9 ISOgrk3',
    tags: ['?', 'w', 'omega'],
***REMOVED***,
  {
    name: 'thetasym',
    number: 977,
    description: 'greek small letter theta symbol, U+03D1 NEW',
    tags: ['?', '0', 'theta'],
***REMOVED***,
  {
    name: 'upsih',
    number: 978,
    description: 'greek upsilon with hook symbol, U+03D2 NEW',
    tags: ['?', 'y', 'hook', 'upsilon'],
***REMOVED***,
  {
    name: 'piv',
    number: 982,
    description: 'greek pi symbol, U+03D6 ISOgrk3',
    tags: ['?', 'pi'],
***REMOVED***,
  {
    name: 'bull',
    number: 8226,
    description: 'bullet = black small circle, U+2022 ISOpub ',
    tags: ['•', '*', 'bullet'],
***REMOVED***,
  {
    name: 'hellip',
    number: 8230,
    description: 'horizontal ellipsis = three dot leader, U+2026 ISOpub ',
    tags: ['…', '...'],
***REMOVED***,
  {
    name: 'prime',
    number: 8242,
    description: 'prime = minutes = feet, U+2032 ISOtech',
    tags: ["'", "'", '`', 'prime'],
***REMOVED***,
  {
    name: 'Prime',
    number: 8243,
    description: 'double prime = seconds = inches, U+2033 ISOtech',
    tags: ['?', '"', 'double', "''"],
***REMOVED***,
  {
    name: 'oline',
    number: 8254,
    description: 'overline = spacing overscore, U+203E NEW',
    tags: ['?', 'overline', 'overscore', '_'],
***REMOVED***,
  {
    name: 'frasl',
    number: 8260,
    description: 'fraction slash, U+2044 NEW',
    tags: ['/', '/', 'fraction', 'slash'],
***REMOVED***,
  {
    name: 'weierp',
    number: 8472,
    description: 'script capital P = power set = Weierstrass p, U+2118 ISOamso',
    tags: ['P', 'P', 'power'],
***REMOVED***,
  {
    name: 'image',
    number: 8465,
    description: 'blackletter capital I = imaginary part, U+2111 ISOamso',
    tags: ['I', 'blackletter', 'I', 'imaginary'],
***REMOVED***,
  {
    name: 'real',
    number: 8476,
    description: 'blackletter capital R = real part symbol, U+211C ISOamso',
    tags: ['R', 'R', 'blackletter', 'real', 'part'],
***REMOVED***,
  {
    name: 'trade',
    number: 8482,
    description: 'trade mark sign, U+2122 ISOnum',
    tags: ['™', 'trade', 'mark', 'tm'],
***REMOVED***,
  {
    name: 'alefsym',
    number: 8501,
    description: 'alef symbol = first transfinite cardinal, U+2135 NEW',
    tags: ['?', 'alef', 'transfinite', 'n'],
***REMOVED***,
  {
    name: 'larr',
    number: 8592,
    description: 'leftwards arrow, U+21',
    tags: ['?', '<-', '<', 'leftwards', 'arrow'],
***REMOVED***,
  {
    name: 'rarr',
    number: 8594,
    description: 'rightwards arrow, U+2192 ISOnum',
    tags: ['?', '->', '>', 'rightwards', 'arrow'],
***REMOVED***,
  {
    name: 'darr',
    number: 8595,
    description: 'downwards arrow, U+2193 ISOnum',
    tags: ['?', 'downwards', 'arrow'],
***REMOVED***,
  {
    name: 'harr',
    number: 8596,
    description: 'left right arrow, U+2194 ISOamsa',
    tags: ['?', '<->', 'right', '<>', 'left', 'arrow'],
***REMOVED***,
  {
    name: 'crarr',
    number: 8629,
    description:
      'downwards arrow with corner leftwards = carriage return, U+21B5 NEW',
    tags: [
      '?',
      'downwards',
      'arrow',
      'leftwards',
      'carriage',
      'return',
      'enter',
    ],
***REMOVED***,
  {
    name: 'lArr',
    number: 8656,
    description: 'leftwards double arrow, U+21D0 ISOtech.',
    tags: ['?', 'double', 'arrow', '<', '<-', '<='],
***REMOVED***,
  {
    name: 'uarr',
    number: 8593,
    description: 'upwards arrow, U+2191 ISOnum',
    tags: ['upwards', 'arrow'],
***REMOVED***,
  {
    name: 'uArr',
    number: 8657,
    description: 'upwards double arrow, U+21D1 ISOamsa',
    tags: ['?', 'upwards', 'double', 'arrow'],
***REMOVED***,
  {
    name: 'rArr',
    number: 8658,
    description: 'rightwards double arrow, U+21D2 ISOtech.',
    tags: ['?', '>', '->', 'rightwards', 'double', '=>', 'arrow'],
***REMOVED***,
  {
    name: 'dArr',
    number: 8659,
    description: 'downwards double arrow, U+21D3 ISOamsa',
    tags: ['?', 'downwards', 'double', 'arrow'],
***REMOVED***,
  {
    name: 'hArr',
    number: 8660,
    description: 'left right double arrow, U+21D4 ISOamsa',
    tags: ['?', '<>', '<=>', '<->', 'left', 'right', 'double', 'arrow'],
***REMOVED***,
  {
    name: 'forall',
    number: 8704,
    description: 'for all, U+2200 ISOtech',
    tags: ['?', 'all', 'A'],
***REMOVED***,
  {
    name: 'part',
    number: 8706,
    description: 'partial differential, U+2202 ISOtech ',
    tags: ['?', 'partial', 'differential', 'd'],
***REMOVED***,
  {
    name: 'exist',
    number: 8707,
    description: 'there exists, U+2203 ISOtech',
    tags: ['?', 'e', 'exists'],
***REMOVED***,
  {
    name: 'empty',
    number: 8709,
    description: 'empty set = null set = diameter, U+2205 ISOamso',
    tags: ['Ø', 'o', 'empty', 'set', 'null', 'diameter'],
***REMOVED***,
  {
    name: 'nabla',
    number: 8711,
    description: 'nabla = backward difference, U+2207 ISOtech',
    tags: ['?', 'nabla', 'difference', 'triangle'],
***REMOVED***,
  {
    name: 'isin',
    number: 8712,
    description: 'element of, U+2208 ISOtech',
    tags: ['?', 'element', 'e'],
***REMOVED***,
  {
    name: 'notin',
    number: 8713,
    description: 'not an element of, U+2209 ISOtech',
    tags: ['?', 'e', 'not', 'element'],
***REMOVED***,
  {
    name: 'ni',
    number: 8715,
    description: 'contains as member, U+220B ISOtech',
    tags: ['?', 'contains', 'member', 'e'],
***REMOVED***,
  {
    name: 'prod',
    number: 8719,
    description: 'n-ary product = product sign, U+220F ISOamsb',
    tags: ['?', 'n-ary', 'product', 'n'],
***REMOVED***,
  {
    name: 'sum',
    number: 8721,
    description: 'n-ary sumation, U+2211 ISOamsb',
    tags: ['?', 'e', 'n-ary', 'sumation'],
***REMOVED***,
  {
    name: 'minus',
    number: 8722,
    description: 'minus sign, U+2212 ISOtech',
    tags: ['-', '-', 'minus'],
***REMOVED***,
  {
    name: 'lowast',
    number: 8727,
    description: 'asterisk operator, U+2217 ISOtech',
    tags: ['*', 'asterisk', '*', 'bullet'],
***REMOVED***,
  {
    name: 'radic',
    number: 8730,
    description: 'square root = radical sign, U+221A ISOtech',
    tags: ['v', 'square', 'root', 'y', '^'],
***REMOVED***,
  {
    name: 'prop',
    number: 8733,
    description: 'proportional to, U+221D ISOtech',
    tags: ['?', 'proportional'],
***REMOVED***,
  {
    name: 'infin',
    number: 8734,
    description: 'infinity, U+221E ISOtech',
    tags: ['8', 'infinity'],
***REMOVED***,
  {
    name: 'ang',
    number: 8736,
    description: 'angle, U+2220 ISOamso',
    tags: ['?', 'angle', '<'],
***REMOVED***,
  {
    name: 'and',
    number: 8743,
    description: 'logical and = wedge, U+2227 ISOtech',
    tags: ['?', 'logical', 'and', 'wedge', '^'],
***REMOVED***,
  {
    name: 'or',
    number: 8744,
    description: 'logical or = vee, U+2228 ISOtech',
    tags: ['?', 'logical', 'or', 'vee'],
***REMOVED***,
  {
    name: 'cap',
    number: 8745,
    description: 'intersection = cap, U+2229 ISOtech',
    tags: ['n', 'intersection', 'cap'],
***REMOVED***,
  {
    name: 'cup',
    number: 8746,
    description: 'union = cup, U+222A ISOtech',
    tags: ['?', 'union', 'cup'],
***REMOVED***,
  {
    name: 'int',
    number: 8747,
    description: 'integral, U+222B ISOtech',
    tags: ['?', 'integral', 'f'],
***REMOVED***,
  {
    name: 'there4',
    number: 8756,
    description: 'therefore, U+2234 ISOtech',
    tags: ['?', 'therefore'],
***REMOVED***,
  {
    name: 'sim',
    number: 8764,
    description: 'tilde operator = varies with = similar to, U+223C ISOtech',
    tags: ['~', 'tilde', '~', 'similar'],
***REMOVED***,
  {
    name: 'cong',
    number: 8773,
    description: 'approximately equal to, U+2245 ISOtech',
    tags: ['?', 'approximately', 'equal', '=', '~'],
***REMOVED***,
  {
    name: 'asymp',
    number: 8776,
    description: 'almost equal to = asymptotic to, U+2248 ISOamsr',
    tags: ['˜', 'almost', '~', '~~', '=', 'equal'],
***REMOVED***,
  {
    name: 'ne',
    number: 8800,
    description: 'not equal to, U+2260 ISOtech',
    tags: ['?', 'not', 'equal', '='],
***REMOVED***,
  {
    name: 'equiv',
    number: 8801,
    description: 'identical to, U+2261 ISOtech',
    tags: ['=', 'identical', '='],
***REMOVED***,
  {
    name: 'le',
    number: 8804,
    description: 'less-than or equal to, U+2264 ISOtech',
    tags: ['=', 'less-than', 'equal', '<=', '=<', '<', '='],
***REMOVED***,
  {
    name: 'ge',
    number: 8805,
    description: 'greater-than or equal to, U+2265 ISOtech',
    tags: ['=', 'greater-than', 'equal', '>=', '=>', '=', '>'],
***REMOVED***,
  {
    name: 'sub',
    number: 8834,
    description: 'subset of, U+2282 ISOtech',
    tags: ['?', 'subset', 'c'],
***REMOVED***,
  {
    name: 'sup',
    number: 8835,
    description: 'superset of, U+2283 ISOtech',
    tags: ['?', 'superset', 'c'],
***REMOVED***,
  {
    name: 'nsub',
    number: 8836,
    description: 'not a subset of, U+2284 ISOamsn',
    tags: ['?', 'c', 'not', 'subset'],
***REMOVED***,
  {
    name: 'sube',
    number: 8838,
    description: 'subset of or equal to, U+2286 ISOtech',
    tags: ['?', 'subset', 'equal', 'c', '='],
***REMOVED***,
  {
    name: 'supe',
    number: 8839,
    description: 'superset of or equal to, U+2287 ISOtech',
    tags: ['?', 'c', 'superset', 'equal', '='],
***REMOVED***,
  {
    name: 'oplus',
    number: 8853,
    description: 'circled plus = direct sum, U+2295 ISOamsb',
    tags: ['?', 'circled', 'plus', '+', 'O', '0'],
***REMOVED***,
  {
    name: 'otimes',
    number: 8855,
    description: 'circled times = vector product, U+2297 ISOamsb',
    tags: ['?', 'circled', 'times', 'vector', 'x', '*', 'o', '0'],
***REMOVED***,
  {
    name: 'perp',
    number: '8869',
    description: 'up tack = orthogonal to = perpendicular, U+22A5 ISOtech',
    tags: ['?', 'up', '|', 'orthogonal', 'perpendicular'],
***REMOVED***,
  {
    name: 'sdot',
    number: '8901',
    description: 'dot operator, U+22C5 ISOamsb',
    tags: ['·', '.', 'dot', '*', 'bullet'],
***REMOVED***,
  {
    name: 'lceil',
    number: '8968',
    description: 'left ceiling = apl upstile, U+2308 ISOamsc ',
    tags: ['?', '[', 'ceiling'],
***REMOVED***,
  {
    name: 'rceil',
    number: '8969',
    description: 'right ceiling, U+2309 ISOamsc ',
    tags: ['?', ']', 'right'],
***REMOVED***,
  {
    name: 'lfloor',
    number: '8970',
    description: 'left floor = apl downstile, U+230A ISOamsc ',
    tags: ['?', '[', 'floor'],
***REMOVED***,
  {
    name: 'rfloor',
    number: '8971',
    description: 'right floor, U+230B ISOamsc ',
    tags: ['?', ']', 'right', 'floor'],
***REMOVED***,
  {
    name: 'lang',
    number: '9001',
    description: 'left-pointing angle bracket = bra, U+2329 ISOtech',
    tags: ['<', '<', 'angle', 'bracket'],
***REMOVED***,
  {
    name: 'rang',
    number: '9002',
    description: 'right-pointing angle bracket = ket, U+232A ISOtech',
    tags: ['>', '>', 'angle', 'bracket'],
***REMOVED***,
  {
    name: 'loz',
    number: '9674',
    description: 'lozenge, U+25CA ISOpub',
    tags: ['?', '<>', 'lozenge', 'diamond'],
***REMOVED***,
  {
    name: 'spades',
    number: '9824',
    description: 'black spade suit, U+2660 ISOpub',
    tags: ['?', 'spade', 'card', 'cards'],
***REMOVED***,
  {
    name: 'clubs',
    number: '9827',
    description: 'black club suit = shamrock, U+2663 ISOpub',
    tags: ['?', 'club', 'shamrock', 'card', 'cards'],
***REMOVED***,
  {
    name: 'hearts',
    number: '9829',
    description: 'black heart suit = valentine, U+2665 ISOpub',
    tags: ['?', 'heart', 'valentine', 'card', 'cards'],
***REMOVED***,
  {
    name: 'diams',
    number: '9830',
    description: 'black diamond suit, U+2666 ISOpub',
    tags: ['?', 'card', 'cards', 'diamond'],
***REMOVED***,
  {
    name: 'quot',
    number: '34',
    description: 'quotation mark = APL quote, U+0022 ISOnum',
    tags: ['"', 'quotation'],
***REMOVED***,
  {
    name: 'amp',
    number: '38',
    description: 'ampersand, U+0026 ISOnum',
    tags: ['&', '&', 'and', 'ampersand'],
***REMOVED***,
  {
    name: 'lt',
    number: '60',
    description: 'less-than sign, U+003C ISOnum',
    tags: ['<', 'less-than', '<', 'left', 'arrow'],
***REMOVED***,
  {
    name: 'gt',
    number: '62',
    description: 'greater-than sign, U+003E ISOnum',
    tags: ['>', '>', 'greater-than'],
***REMOVED***,
  {
    name: 'OElig',
    number: '338',
    description: 'latin capital ligature OE, U+0152 ISOlat2',
    tags: ['Œ', 'OE'],
***REMOVED***,
  {
    name: 'oelig',
    number: '339',
    description: 'latin small ligature oe, U+0153 ISOlat2',
    tags: ['œ', 'oe'],
***REMOVED***,
  {
    name: 'Scaron',
    number: '352',
    description: 'latin capital letter S with caron, U+0160 ISOlat2',
    tags: ['Š', 'S', 'caron'],
***REMOVED***,
  {
    name: 'scaron',
    number: '353',
    description: 'latin small letter s with caron, U+0161 ISOlat2',
    tags: ['š', 's', 'caron'],
***REMOVED***,
  {
    name: 'Yuml',
    number: '376',
    description: 'latin capital letter Y with diaeresis, U+0178 ISOlat2',
    tags: ['Ÿ', 'Y', 'diaeresis'],
***REMOVED***,
  {
    name: 'circ',
    number: '710',
    description: 'modifier letter circumflex accent, U+02C6 ISOpub',
    tags: ['ˆ', 'circumflex', 'accent', '^'],
***REMOVED***,
  {
    name: 'tilde',
    number: '732',
    description: 'small tilde, U+02DC ISOdia',
    tags: ['˜', 'tilde', '~'],
***REMOVED***,
  {
    name: 'ensp',
    number: '8194',
    description: 'en space, U+2002 ISOpub',
    tags: ['en', 'space'],
***REMOVED***,
  {
    name: 'emsp',
    number: '8195',
    description: 'em space, U+2003 ISOpub',
    tags: ['em', 'space'],
***REMOVED***,
  {
    name: 'thinsp',
    number: '8201',
    description: 'thin space, U+2009 ISOpub',
    tags: ['thin', 'space'],
***REMOVED***,
  {
    name: 'zwnj',
    number: '8204',
    description: 'zero width non-joiner, U+200C NEW RFC 2070',
    tags: ['?', ' ', 'zero', 'non-joiner'],
***REMOVED***,
  {
    name: 'zwj',
    number: '8205',
    description: 'zero width joiner, U+200D NEW RFC 2070',
    tags: ['?', ' ', 'zero'],
***REMOVED***,
  {
    name: 'lrm',
    number: '8206',
    description: 'left-to-right mark, U+200E NEW RFC 2070',
    tags: ['?', 'left-to-right', '<>'],
***REMOVED***,
  {
    name: 'rlm',
    number: '8207',
    description: 'right-to-left mark, U+200F NEW RFC 2070',
    tags: ['?', 'right-to-left', '><'],
***REMOVED***,
  {
    name: 'ndash',
    number: '8211',
    description: 'en dash, U+2013 ISOpub',
    tags: ['–', 'n', 'en', 'dash', '-'],
***REMOVED***,
  {
    name: 'mdash',
    number: '8212',
    description: 'em dash, U+2014 ISOpub',
    tags: ['—', 'm', 'em', 'dash', '-'],
***REMOVED***,
  {
    name: 'lsquo',
    number: '8216',
    description: 'left single quotation mark, U+2018 ISOnum',
    tags: ['‘', 'left', 'quotation', 'quote', "'"],
***REMOVED***,
  {
    name: 'rsquo',
    number: '8217',
    description: 'right single quotation mark, U+2019 ISOnum',
    tags: ['’', "'", 'right', 'quotation', 'quote'],
***REMOVED***,
  {
    name: 'sbquo',
    number: '8218',
    description: 'single low-9 quotation mark, U+201A NEW',
    tags: ['‚', ',', 'quotation', 'quote', 'low-9', 'low'],
***REMOVED***,
  {
    name: 'ldquo',
    number: '8220',
    description: 'left double quotation mark, U+201C ISOnum',
    tags: ['“', '"', 'quotation', 'quote'],
***REMOVED***,
  {
    name: 'rdquo',
    number: '8221',
    description: 'right double quotation mark, U+201D ISOnum',
    tags: ['”', '"', 'double', 'quotation', 'quote'],
***REMOVED***,
  {
    name: 'bdquo',
    number: '8222',
    description: 'double low-9 quotation mark, U+201E NEW',
    tags: ['„', 'double', 'low-9', 'quotation', 'quote', '"'],
***REMOVED***,
  {
    name: 'dagger',
    number: '8224',
    description: 'dagger, U+2020 ISOpub',
    tags: ['†', '+', 'dagger'],
***REMOVED***,
  {
    name: 'Dagger',
    number: '8225',
    description: 'double dagger, U+2021 ISOpub',
    tags: ['‡', 'double', 'dagger', '++', '+'],
***REMOVED***,
  {
    name: 'permil',
    number: '8240',
    description: 'per mille sign, U+2030 ISOtech',
    tags: ['‰', 'per', 'mille', '%'],
***REMOVED***,
  {
    name: 'lsaquo',
    number: '8249',
    description:
      'single left-pointing angle quotation mark, U+2039 ISO proposed',
    tags: ['‹', 'left-pointing', 'angle', '<'],
***REMOVED***,
  {
    name: 'rsaquo',
    number: '8250',
    description:
      'single right-pointing angle quotation mark, U+203A ISO proposed',
    tags: ['›', 'right-pointing', 'angle', '>'],
***REMOVED***,
  {
    name: 'euro',
    number: '8364',
    description: 'euro sign, U+20AC NEW',
    tags: ['€', 'E', '€', 'euro'],
***REMOVED***,
  {
    name: 'teuro',
    number: '8364',
    description: 'euro sign, U+20AC NEW',
    tags: ['€', 'E', '€', '-', 'teurol'],
***REMOVED***,
  {
    name: '-',
    number: '8364',
    description: 'euro sign, U+20AC NEW',
    tags: ['(bracket)'],
***REMOVED***,
]
